import os
import shutil
import urllib.request
import zipfile
import sys
from lib.modules.base import Component
from lib.core.packages import KnownPackage
from lib.utils.logger import Logger

class Neovim(Component):
    def install(self) -> None:
        try:
            Logger.info("Installing Neovim...")
            
            if sys.platform == "win32":
                url = "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-win64.zip"
                archive_name = "nvim.zip"
                
                download_path = "tmp"
                download_file = os.path.join(download_path, archive_name)
                os.makedirs(download_path, exist_ok=True)
                
                Logger.info(f"Downloading {url}...")
                urllib.request.urlretrieve(url, download_file)
                
                install_path = os.path.join(self.platform.get_home_dir(), "nvim")
                if os.path.exists(install_path):
                    shutil.rmtree(install_path)
                os.mkdir(install_path)
                
                Logger.info("Extracting...")
                with zipfile.ZipFile(download_file, 'r') as zip_ref:
                    zip_ref.extractall(install_path)
                
                # Zip contains 'nvim-win64' folder
                bin_path = os.path.join(install_path, "nvim-win64", "bin")
                
                Logger.info(f"Adding {bin_path} to PATH...")
                self.platform.add_to_path(bin_path)
                    
                Logger.ok("Successfully installed Neovim binary")
                
            elif sys.platform == "linux":
                self.platform.install_package(KnownPackage.NEOVIM)
                Logger.ok("Successfully installed Neovim via package manager")
                
            else:
                Logger.err(f"Neovim installation not supported on {sys.platform}")
                return
            
            Logger.info("Installing VSCode Neovim extension...")
            self.platform.install_vscode_extension("asvetliakov.vscode-neovim")
            Logger.ok("Successfully installed VSCode Neovim extension")

            self._configure_neovim()
            
        except Exception as e:
            Logger.err(f"Failed to install Neovim: {e}")
            raise

    def _configure_neovim(self):
        Logger.info("Configuring Neovim...")
        
        if sys.platform == "win32":
            # LOCALAPPDATA is standard for Windows config
            base_dir = os.environ.get("LOCALAPPDATA", os.path.join(self.platform.get_home_dir(), "AppData", "Local"))
            config_dir = os.path.join(base_dir, "nvim")
        else:
            config_dir = os.path.join(self.platform.get_home_dir(), ".config", "nvim")
            
        os.makedirs(config_dir, exist_ok=True)
        init_lua_path = os.path.join(config_dir, "init.lua")
        
        config_content = """-- Default init.lua generated by DevEssentials

-- Set leader key to space
vim.g.mapleader = " "

-- Basic settings
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.ignorecase = true
vim.opt.smartcase = true

-- VSCode Neovim specific settings
if vim.g.vscode then
    -- VSCode extension logic
    -- Add VSCode specific keybindings or settings here
else
    -- Standard Neovim logic
    vim.opt.termguicolors = true
end
"""
        
        if not os.path.exists(init_lua_path):
            try:
                with open(init_lua_path, "w", encoding="utf-8") as f:
                    f.write(config_content)
                Logger.ok(f"Created default init.lua at {init_lua_path}")
            except Exception as e:
                Logger.warn(f"Failed to create init.lua: {e}")
        else:
            Logger.info(f"init.lua already exists at {init_lua_path}, skipping creation.")
