-- Default init.lua generated by DevEssentials

-- Set leader key to space
vim.g.mapleader = " "

-- Basic settings
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.signcolumn = "yes"
vim.opt.swapfile = false
vim.opt.cursorline = true
--vim.opt.winborder = "rounded"
vim.opt.ignorecase = true
vim.opt.smartcase = true

if vim.g.vscode then
    local vscode = require('vscode')
    local function code_action(cmd)
        return function() vscode.call(cmd) end
    end

    -- NAVIGATION -----------------------------------------------------------
    
    -- Switch buffers (Mapped to VS Code tabs)
    vim.keymap.set('n', '<S-h>', code_action('workbench.action.previousEditor'))
    vim.keymap.set('n', '<S-l>', code_action('workbench.action.nextEditor'))

    -- Splits
    vim.keymap.set('n', '<leader>v', code_action('workbench.action.moveEditorToRightGroup'))
    vim.keymap.set('n', '<leader>s', code_action('workbench.action.moveEditorToBelowGroup'))

    -- Panes / Window Groups
    vim.keymap.set('n', '<leader>h', code_action('workbench.action.focusLeftGroup'))
    vim.keymap.set('n', '<leader>j', code_action('workbench.action.focusBelowGroup'))
    vim.keymap.set('n', '<leader>k', code_action('workbench.action.focusAboveGroup'))
    vim.keymap.set('n', '<leader>l', code_action('workbench.action.focusRightGroup'))

    -- NICE TO HAVE ---------------------------------------------------------
    
    -- Save and Quit
    vim.keymap.set('n', '<leader>w', code_action('workbench.action.files.save')) -- :w!
    vim.keymap.set('n', '<leader>q', code_action('workbench.action.closeActiveEditor')) -- :q!
    vim.keymap.set('n', '<leader>x', function() -- :x! (Save and Close)
        vscode.call('workbench.action.files.save')
        vscode.call('workbench.action.closeActiveEditor')
    end)

    -- Diagnostics (Error navigation)
    vim.keymap.set('n', '[d', code_action('editor.action.marker.prev'))
    vim.keymap.set('n', ']d', code_action('editor.action.marker.next'))

    -- Code Actions / Quick Fix
    vim.keymap.set('n', '<leader>ca', code_action('editor.action.quickFix'))

    -- File Search (Quick Open)
    vim.keymap.set('n', '<leader>f', code_action('workbench.action.quickOpen'))

    -- Formatting
    vim.keymap.set('n', '<leader>lf', code_action('editor.action.formatDocument'))

    -- Hover Definition
    vim.keymap.set('n', 'gh', code_action('editor.action.showDefinitionPreviewHover'))

    -- VISUAL MODE MAPPINGS -------------------------------------------------
    
    -- Stay in visual mode while indenting
    vim.keymap.set('v', '<', code_action('editor.action.outdentLines'))
    vim.keymap.set('v', '>', code_action('editor.action.indentLines'))

    -- Move selected lines up/down
    vim.keymap.set('v', 'J', code_action('editor.action.moveLinesDownAction'))
    vim.keymap.set('v', 'K', code_action('editor.action.moveLinesUpAction'))

    -- Toggle Comment
    vim.keymap.set('v', '<leader>c', code_action('editor.action.commentLine'))
else
    -- NAVIGATION -----------------------------------------------------------

    -- Switch buffers (Mapped to previous/next buffer)
    vim.keymap.set('n', '<S-h>', '<cmd>bprevious<CR>', { desc = "Previous Buffer" })
    vim.keymap.set('n', '<S-l>', '<cmd>bnext<CR>', { desc = "Next Buffer" })

    -- Splits
    vim.keymap.set('n', '<leader>v', '<cmd>vsplit<CR>', { desc = "Vertical Split" })
    vim.keymap.set('n', '<leader>s', '<cmd>split<CR>', { desc = "Horizontal Split" })

    -- Panes / Window Groups (Standard Vim window navigation)
    vim.keymap.set('n', '<leader>h', '<C-w>h', { desc = "Focus Left" })
    vim.keymap.set('n', '<leader>j', '<C-w>j', { desc = "Focus Down" })
    vim.keymap.set('n', '<leader>k', '<C-w>k', { desc = "Focus Up" })
    vim.keymap.set('n', '<leader>l', '<C-w>l', { desc = "Focus Right" })

    -- NICE TO HAVE ---------------------------------------------------------

    -- Save and Quit
    vim.keymap.set('n', '<leader>w', '<cmd>w<CR>', { desc = "Save" })
    vim.keymap.set('n', '<leader>q', '<cmd>q<CR>', { desc = "Quit" })
    vim.keymap.set('n', '<leader>x', '<cmd>x<CR>', { desc = "Save and Quit" })

    -- Diagnostics (Using built-in Neovim diagnostic API)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = "Previous Diagnostic" })
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = "Next Diagnostic" })

    -- Code Actions (Using built-in LSP)
    vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action, { desc = "Code Action" })

    -- File Search (Assuming Telescope is installed - replace with your picker)
    vim.keymap.set('n', '<leader>f', '<cmd>Telescope find_files<CR>', { desc = "Find Files" })

    -- Formatting (Using built-in LSP)
    vim.keymap.set('n', '<leader>lf', vim.lsp.buf.format, { desc = "Format Document" })

    -- Hover Definition (Using built-in LSP)
    vim.keymap.set('n', 'gh', vim.lsp.buf.hover, { desc = "Hover Documentation" })

    -- VISUAL MODE MAPPINGS -------------------------------------------------

    -- Stay in visual mode while indenting (The 'gv' command reselects the last area)
    vim.keymap.set('v', '<', '<gv', { desc = "Outdent" })
    vim.keymap.set('v', '>', '>gv', { desc = "Indent" })

    -- Move selected lines up/down (Magic Vim incantations)
    -- This moves the selection, re-indents it (=), and keeps selection (gv)
    vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = "Move Selection Down" })
    vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = "Move Selection Up" })

    -- Toggle Comment 
    -- (Neovim 0.10+ has built-in commenting via 'gcc', but here is a manual map)
    -- If you use 'numToStr/Comment.nvim', use the plugin command instead.
    vim.keymap.set('v', '<leader>c', 'gc', { remap = true, desc = "Toggle Comment" })
end
